# fly.toml app configuration file generated for nerdy-snippetbox on 2023-09-17T21:28:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nerdy-snippetbox"
primary_region = "atl"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
